### ISSUE TITLE
Test Hardhat with EthereumJS mode in third-party repos

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/edr#183]
**Definition of Done**
- [x] Test in [OpenZeppelin](https://github.com/OpenZeppelin/openzeppelin-contracts)
- [x] Test in https://github.com/NexusMutual/smart-contracts
- [x] Test in https://github.com/ProjectOpenSea/seaport/ 
- [x] Test in https://github.com/smartcontractkit/chainlink/tree/develop/contracts
- [x] Test in https://github.com/rocket-pool/rocketpool/
- [x] Test in https://github.com/neptune-mutual-blue/protocol 
- [x] Test in https://github.com/safe-global/safe-contracts
- [x] Test in https://github.com/taikoxyz/taiko-mono
- [x] Decide whether to test more based on https://www.notion.so/nomicfoundation/Testing-with-real-projects-bd896ef0b11c45fbb41eeb6df16e6584

If more test repositories are needed, then these searches help:
https://github.com/search?q=path%3A**%2Fhardhat.config.js&type=code&ref=advsearch
https://github.com/search?q=path%3A**%2Fhardhat.config.ts&type=code&ref=advsearch

**Comment by agostbiro** [comment]
# Results from today's benchmarking

Test command: `npx hardhat test`. The reported time is a median of 3 runs.

## [Uniswap/v3-core](https://github.com/Uniswap/v3-core) @ `d8b1c63`

#### hardhat 2.2.0 (from lockfile)

71 seconds

#### hardhat [b2a551f73](https://github.com/nomicFoundation/hardhat/commits/b2a551f73) (main)

85 seconds ⚠️ 

#### hardhat [a344ebedf](https://github.com/nomicFoundation/hardhat/commits/a344ebedf) (edr/misc/benchmark-cli)

91 seconds 🚨 

## [openzeppelin-contracts](https://github.com/OpenZeppelin/openzeppelin-contracts) @ `6383299d`

Fails in `rethnet/main`: https://github.com/NomicFoundation/edr/issues/205

## [NexusMutual/smart-contracts](https://github.com/NexusMutual/smart-contracts) @ `7ff5f3a4`

Uses Hardhat `2.13.0` and it doesn't work with the latest Hardhat (`2.18.1`) due to various plugin errors that I wasn't able to resolve in reasonable time.

## [seaport](https://github.com/ProjectOpenSea/seaport/) @ `6d8bf57d`

Uses Hardhat `2.2.0` and fails with https://github.com/NomicFoundation/hardhat/issues/4484 when upgrading to the latest Hardhat (`2.18.1`)

## [synthetix](https://github.com/Synthetixio/synthetix) @ `3040126f`

#### hardhat [b2a551f73](https://github.com/nomicFoundation/hardhat/commits/b2a551f73) (main)

Takes over an hour per run, still running

#### hardhat [a344ebedf](https://github.com/nomicFoundation/hardhat/commits/a344ebedf) (edr/misc/benchmark-cli)

TBD

**Comment by agostbiro** [comment]
Current status

## [Uniswap/v3-core](https://github.com/Uniswap/v3-core) @ `d8b1c63` ✅ 

Test suite passes with `rethnet/main` @ `a08c12d`.

## [openzeppelin-contracts](https://github.com/OpenZeppelin/openzeppelin-contracts) @ `6383299d` ✅ 

Test suite passes with `rethnet/main` @ `a08c12d`.

## [NexusMutual/smart-contracts](https://github.com/NexusMutual/smart-contracts) @ `7ff5f3a4` ❌

Uses Hardhat `2.13.0` and it doesn't work with Hardhat `2.18.1` due to various plugin errors.

## [seaport](https://github.com/ProjectOpenSea/seaport/) @ `6d8bf57d` ❌

Uses Hardhat `2.12.1-ir.0` and fails with https://github.com/NomicFoundation/hardhat/issues/4484 when upgrading to Hardhat `2.18.1`.

## [synthetix](https://github.com/Synthetixio/synthetix) @ `3040126f` ❌

Uses Hardhat `2.12.7`. Sporadic failure of one test with `main` and `rethnet/main`: https://github.com/NomicFoundation/edr/issues/207#issuecomment-1772931966

**Comment by agostbiro** [comment]
Posted latest performance numbers to https://github.com/NomicFoundation/edr/issues/195

**Comment by Wodann** [comment]
## [chainlink/contracts](https://github.com/smartcontractkit/chainlink/tree/develop/contracts) @ `b7a2c77` ❓

Test suite fails with Hardhat ~2.18.1 due to:

<details>

<summary>Error message</summary>

```ruby
   puts "Hello World"
```

</details>


:

**Comment by Wodann** [comment]
## [rocketpool](https://github.com/rocket-pool/rocketpool/) @ `6a9dbfd`

Test suite passes with Hardhat ^2.12.2.

Test suite passes with `rethnet/main` @ `bf886a4`.

**Comment by Wodann** [comment]
## hardhat-tracer @ ``

Both local Hardhat version and `edr/main` @ `9f3303c91` have one failing test:

```
6 passing (695ms)
  1 failing

  1) Hello
       should run a test:
     Error: VM Exception while processing transaction: reverted with reason string 'hello'
    at Hello.hi2 (contracts/Hello.sol:52)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at listOnTimeout (node:internal/timers:540:9)
    at processTimers (node:internal/timers:514:7)
    at async HardhatNode._finalizeBlockResult (/home/ubuntu/dev/hardhat-tracer/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1521:19)
    at async HardhatNode.mineBlock (/home/ubuntu/dev/hardhat-tracer/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:405:20)
    at async EthModule._sendTransactionAndReturnHash (/home/ubuntu/dev/hardhat-tracer/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1432:18)
    at async HardhatNetworkProvider.request (/home/ubuntu/dev/hardhat-tracer/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:124:18)
    at async TracerWrapper.request (/home/ubuntu/dev/hardhat-tracer/src/wrapper.ts:30:16)
    at async EthersProviderWrapper.send (/home/ubuntu/dev/hardhat-tracer/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
```
