### ISSUE TITLE
Setup keys in CI for releasing npm packages

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/edr#184]
**Depends on**
- [ ] #63 

**Definition of Done**
Set up npm keys for releasing `edr` npm packages from a GitHub CI workflow

**Comment by Wodann** [comment]
@agostbiro will send the details to Pato

**Comment by agostbiro** [comment]
I think it would be best to use a separate Github Actions environment for the EDR release job, so that other jobs in the repo don't have access to the sensitive NPM tokens.

@alcuadrado could you please [add an environment](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#creating-an-environment) called `edr-release`, with the following secret environment variables:

- `IGNORED_ORG_NPM_TOKEN` for the @ignored NPM org
- `NOMICFOUNDATION_ORG_NPM_TOKEN` for the @nomicfoundation NPM org.

Feel free to adjust the names as you see fit, I'll adopt the changes.
