### ISSUE TITLE
OpenZeppelin test fails with `Unmatched rethnet exceptional halt: 7`

### ISSUE THREAD

**Issue by agostbiro** [NomicFoundation/edr#205]
OpenZeppelin test fails with `Unmatched rethnet exceptional halt: 7` in `rethnet/main`.

**Steps to reproduce**

1. Check out https://github.com/OpenZeppelin/openzeppelin-contracts @ `6383299d`
2. Link `openzeppelin-contracts` to `rethnet/main` version of Hardhat (tested with `a344ebedf `)
3. Run `npx hardhat test --grep "fails deploying a contract in an existent address"` in the OpenZeppelin repo

**Expected result**

The test passes.

**Actual result**

The test fails with `Unmatched rethnet exceptional halt: 7`.

**Notes**

- There are other test cases in the repo that fail with the same exception.
- The test succeeds with Hardhat `2.17.3`.

**Comment by Wodann** [comment]
I didn't have time to look into this yet, but I know what the cause is from prior experience:

We have [a mapping of EDR errors to Hardhat errors](https://github.com/NomicFoundation/hardhat/blob/rethnet/main/packages/hardhat-core/src/internal/hardhat-network/provider/vm/exit.ts#L27). That one is missing [this `ExceptionalHalt`](https://github.com/NomicFoundation/hardhat/blob/rethnet/main/crates/edr_evm_napi/index.d.ts#L358).

I'm not sure which EthereumJS error is equivalent to that. You'd need to take a look at `revm` and Hardhat/EthereumJS to see
