### ISSUE TITLE
HardhatError: HH604: Error running JSON-RPC server.

### ISSUE THREAD

**Issue by Nand2com** [NomicFoundation/edr#345]
I use infura. Everything worked for me, I installed hardhat gas reporter and it broke. I have tried to create a new project but the error continues. I have not exceeded the number of requests in infura. Is there any solution?

Error -> HardhatError: HH604: Error running JSON-RPC server: The Http server returned error status code: HTTP status client error (429 Too Many Requests) for url.

Version -> 2.22.2

Comand ->  npx hardhat node

![errorInfura](https://github.com/NomicFoundation/hardhat/assets/60442629/642a3404-c88d-48ce-b106-b556ac284140)

**Comment by Nand2com** [comment]
> Hey, can we get some more details:
> 
> * Are you attempting to run a Hardhat node by forking mainnet? If so what block number are you using?
> * Does this same issue happen with Sepolia?

The mainnet is being forked, I don't use the block number. It seems like some kind of incompatibility with infura or that infura is filtering me for some reason. With alchemy it works.

**Comment by agostbiro** [comment]
> The mainnet is being forked, I don't use the block number. It seems like some kind of incompatibility with infura or that infura is filtering me for some reason. With alchemy it works.

Thanks for the quick reply! I tried to reproduce by running the Hardhat and EDR test suites with Infura (normally we use Alchemy), but couldn't repro unfortunately, even though these test suites make heavy use of remote RPC calls. 

For background, when a remote provider returns the 429 Too Many Requests HTTP status code, it's a signal that we're getting rate limited by the provider. To get around this, we wait for some time and then retry again in the RPC client. But if after a preconfigured number of times we still get the 429 response code, we give up and you get the error described in the issue.

It's possible that we have to adjust how long we wait and how many times we retry to make certain workloads work with Infura. In order to determine how to tune the parameters, we'd need a public repository where the issue is reproducible. Does anybody have one?

**Comment by davedavinci** [comment]
I use the same technique: forking mainnet from Infura.
I regularly use HH 2.20.1 with this method and never had any problems.
HH 2.22.2 is the first version I try past 2.20.1 and it gives me this error.

**Comment by XDapps** [comment]
I'm having the same issue:

Infura Error:
`[Error: The Http server returned error status code: HTTP status client error (429 Too Many Requests) for url (https://polygon-mainnet.infura.io/v3/33f6cca2bd884901ac2b121e9f479ebc)] {
  code: 'GenericFailure'
}`

QuickNode Error:
`[Error: The response reported error `-32012`: `credits limited to 330/sec`. (optional data: None). Request: [{"id":0,"jsonrpc":"2.0","method":"eth_getBalance","params"....`

**Comment by MetaMmodern** [comment]
I'm getting the same issue with same scenario with Infura with same 2.22.2 version.

More context: a while ago I was using macOS, where forking happened fine and was regularly happening fine. Then my friend tried to fork mainnet using windows machine, he couldn't. Then I tried using my Windows 10 machine and I couldn't.
Then, yesterday, I pulled my own project, did the setup, ran fork and it just worked! Then again and again. Today I tried again and it worked, but after a couple of hours when I tried one more time it failed. Then it failed again and it keeps failing right now. 

It's some kind of phantom bug. I also notice: first time I pulled my oroject I installed packages using `npm ci`. It was working, but Hardhat vscode extension asked me to delete lock file and modules and install everything again, which I did and the bug started happening again after using `npm i`.
I would've posted a diff, but it's lock file with 12k lines of code, so if anyone needs it and knows how to attach it here safely let me know.

**Comment by XDapps** [comment]
What version of Ethers are you using? I can only replicate the problem with ether V6 and above, when I revert back to older projects using V5 it still works.

**Comment by MetaMmodern** [comment]
@XDapps I see ethers v6 in my package.json. Let me try combination of hh 2.20.1 and ethers v6, I'll get back with results, currently installing..

**Comment by fvictorio** [comment]
> And don't run npx hardhat, use the hardhat shorthand instead (hh), because npx always defaults to latest version (which is 2.22.2) while hh uses version from the project.

Just FYI, this is not correct. `npx hardhat` will use the locally installed version, if it exists. We still recommend using `hh` because it's a bit faster and supports autocompletion, but `npx hardhat` should have the same behavior when it comes to which version is used, assuming you do have Hardhat installed.

**Comment by MetaMmodern** [comment]
> > And don't run npx hardhat, use the hardhat shorthand instead (hh), because npx always defaults to latest version (which is 2.22.2) while hh uses version from the project.
> 
> Just FYI, this is not correct. `npx hardhat` will use the locally installed version, if it exists. We still recommend using `hh` because it's a bit faster and supports autocompletion, but `npx hardhat` should have the same behavior when it comes to which version is used, assuming you do have Hardhat installed.

yup, you're right, seems I was just accidentally trying `npx hardhat` in a non-hardhat folder, that's why it was askign to install 2.22. Thanks!

**Comment by fvictorio** [comment]
Question for people running into this: does this happen when the node is starting, or does the node start and then after using it for a while you get this error?

**Comment by MetaMmodern** [comment]
> Question for people running into this: does this happen when the node is starting, or does the node start and then after using it for a while you get this error?

It happens when node tries to start. It never gets to "running" state and throws an error.

**Comment by XDapps** [comment]
It happens when the node is starting. The startup never completes successfully.

**Comment by agostbiro** [comment]
Hi, thanks for all the input!

We’ve released [EDR v0.3.4](https://github.com/NomicFoundation/hardhat/blob/91c94cdbf1f2f4e7ce07fc54a463f2d8491047f1/crates/edr_napi/CHANGELOG.md#034) with improvements that should help with this issue.

If you’re using the latest Hardhat release, in order to use EDR v0.3.4, you can remove your `node_modules` directory and npm/yarn/pnpm lock file and reinstall your dependencies. You can verify that you’re using the correct version of EDR by running the following command: 

`npm ls @nomicfoundation/edr `

It should print `0.3.4`.

Also, if anyone’s got a public repo where the problem is consistently reproducible, please share it!

**Comment by Wodann** [comment]
As we haven't heard any new reports since the release of EDR v0.3.4, we're closing this issue.

If anyone runs into this issue again with EDR v0.3.4 or later, please leave a comment and we'll re-open the issue.
