### ISSUE TITLE
eth_increaseTime only allows positive values

### ISSUE THREAD

**Issue by YoshihitoAso** [NomicFoundation/edr#355]
For hardhat-network's `eth_increaseTime` RPC, past versions (such as 2.18) allowed negative values as input parameters, but the current version (2.22) no longer allows this.

v2.18: https://github.com/NomicFoundation/hardhat/blob/hardhat%402.18.0/packages/hardhat-core/src/internal/hardhat-network/provider/modules/evm.ts#L117-L124

- Does the current implementation follow the specification?
- When implementing tests, I may want to set negative values. Can negative values be supported?

**Comment by fvictorio** [comment]
This seems like something that was working just by coincidence. I don't think we ever made the decision of allowing negative increases, because in general we maintain the guarantee that the timestamp of a block is greater than the timestamp of the previous block (or gretar than or queal to, if `allowBlocksWithSameTimestamp` is enabled).

Can you tell us more about your use case? Why do you need blocks with earlier timestamps?

> * Does the current implementation follow the specification?

There is no specification here, because this is a non-standard method.

**Comment by Wodann** [comment]
It sounds like `evm_setNextBlockTimestamp` might be a good API to use in your use case. It allows you to (continuously) set the next block's timestamp to the exact same time that you're looking for.

Would that be a good alternative?

**Comment by fvictorio** [comment]
Hi @YoshihitoAso. I think this is one of those annoying cases where it's hard to say if something is a bug fix or a breaking change.

As far as I remember, we've always forbidden mining blocks with a timestamp lower or equal to the timestamp of the parent block. We eventually added the `allowBlocksWithSameTimetamp` option, because some L2 chains do have blocks with equal timestamps. But as far as I know, blocks that have a lower timestamp are not a thing anywhere. If you think there should be an option to allow this anyway, I suggest opening an issue in the Hardhat repo with that feature request, so that we can gauge how much interest/need for that there is.

I don't know the details of your use case, but my guess is that you might be able to use snapshots or `hardhat_reset` to accomplish what you want. Alternatively, if you need to mine N transactions in blocks with the same timestamp, you could have a helper function that always calls `evm_setNextBlockTimestamp` with the current timestamp before sending the tx.

Hopefully that helps! Glad to answer any question related to this, but I'm going to tentatively close this because I don't think we'll change this behavior.

**Comment by fvictorio** [comment]
> As far as I remember, we've always forbidden mining blocks with a timestamp lower or equal to the timestamp of the parent block.

To expand on this: in pre-EDR versions of Hardhat, we already checked that the argument to `evm_setNextBlockTimestamp` or the optional timestamp for `evm_mine` were greater than the current timestamp (or greater or equal, if `allowBlocksWithSameTimestamp` is enabled). Not having a similar check for `evm_increaseTime` was an oversight.
