### ISSUE TITLE
Support point_evaluation_precompile when hardfork is cancun or later

### ISSUE THREAD

**Issue by dajuguan** [NomicFoundation/edr#364]
### Describe the feature

https://github.com/ethereum/EIPs/blob/master/EIPS/eip-4844.md#point-evaluation-precompile

### Search terms

point evaluation precompile, 4844, eip4844, eip-4844, kzg proof

**Comment by fvictorio** [comment]
Thanks @dajuguan for reporting this.

Note for ourseles: a very minimal test is make an `eth_call` to `0x000000000000000000000000000000000000000a` without any input data. Since the precompile checks that the input data is 192 bytes long, it should revert. Right now it doesn't.

We could also have a test it with a proper proof, but that would be like testing REVM itself, which I don't think makes sense.

**Comment by dajuguan** [comment]
> Thanks @dajuguan for reporting this.
> 
> Note for ourselves: a very minimal test is make an `eth_call` to `0x000000000000000000000000000000000000000a` without any input data. Since the precompile checks that the input data is 192 bytes long, it should revert. Right now it doesn't.
> 
> We could also have a test it with a proper proof, but that would be like testing REVM itself, which I don't think makes sense.

FYI, I've written a [simple test case in js and python](https://github.com/dajuguan/solidity/tree/main/eip-4844-kzg).
