### ISSUE TITLE
BASEFEE always returns 0 when running an `eth_call` with a London block

### ISSUE THREAD

**Issue by alcuadrado** [NomicFoundation/edr#462]
I'm opening this issue to document a limitation in our `eth_call` implementation.

Transcript of an internal conversation in the ethereumjs discord:

> @alcuadrado:
> I found another limitation of the vm wrt to geth's and other's
> eth_call should run an EVM message in the context of a block and return its return data. Nothing new here.
> 
> This can only be done with runTx in the vm, as runCall has some limitations we've discussed a lot of times.
> 
> runTx requires a tx with a gasPrice/maxFeePerGas&maxPriorityFeePerGas. This value should be 0, and this is how other clients behave.
> 
> If the block where the eth_call is running has a baseFeePerGas, this tx will be rejected, as its fee params would be too low (that 0). We should have a way to disable this check.
> 
> As a workaround, we are creating a new block with baseFeePerGas = 0, but this will also change the value returned by BASEFEE.

**Comment by fvictorio** [comment]
I'm revisiting this, and apparently this matches geth's behavior, at least according to my tests using `geth --dev` and sepolia.

Our rule of thumb is "when in doubt, follow what geth does", so I think we should consider 0 basefee in `eth_call` as expected behavior.

Tentatively closing, but happy to re-open if someone can argue that we should do something different.
